logging.level.root=INFO
logging.level.com.avangrid=INFO
logging.level.org.springframework.security=WARN
logging.level.org.springframework.security.oauth2=WARN
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.orm.jdbc.bind=WARN
spring.jpa.show-sql=false
logging.level.org.springframework.web=INFO

cors.allowed-origins=${FRONTEND_URL:http://localhost:4200}

# =====================================================
# JWT SECURITY
# =====================================================
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://sts.windows.net/aeea9a9c-cd86-4e5c-a3e4-db2be94c0c08/
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://login.microsoftonline.com/aeea9a9c-cd86-4e5c-a3e4-db2be94c0c08/discovery/v2.0/keys
spring.security.oauth2.resourceserver.jwt.audience=api://d6acffb4-c10c-41d1-9209-247df35d7e6d
