spring.application.name=avangrid-backend
server.port=8080

# =====================================================
# AZURE STORAGE (SERVICE PRINCIPAL AUTH)
# =====================================================
azure.storage.account-name=avangridblobsample
azure.storage.container-name=myccassprod
azure.client-id=348c99a4-3662-4c91-b380-6e4f85d82658
azure.tenant-id=aeea9a9c-cd86-4e5c-a3e4-db2be94c0c08
azure.client-secret=${blob-secret}

spring.cloud.azure.keyvault.secret.property-sources[0].endpoint=https://avangridkv.vault.azure.net/

# =====================================================
# JPA COMMON CONFIG
# =====================================================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# =====================================================
# MULTI DB (CMP / NYSEG / RGE)
# =====================================================
datasource.cmp.jdbc-url=jdbc:postgresql://pg-3f03599b-akshayevans1234-579c.j.aivencloud.com:19703/defaultdb
datasource.cmp.username=${cmp-db-username}
datasource.cmp.password=${cmp-db-password}
datasource.cmp.driver-class-name=org.postgresql.Driver

datasource.nyseg.jdbc-url=jdbc:postgresql://pg-39562c9d-akshayms9056-f923.e.aivencloud.com:18784/defaultdb
datasource.nyseg.username=${nyseg-db-username}
datasource.nyseg.password=${nyseg-db-password}
datasource.nyseg.driver-class-name=org.postgresql.Driver

datasource.rge.jdbc-url=jdbc:postgresql://pg-247f6103-akshayvsm9056-ad8d.j.aivencloud.com:23697/defaultdb
datasource.rge.username=${rge-db-username}
datasource.rge.password=${rge-db-password}
datasource.rge.driver-class-name=org.postgresql.Driver

datasource.cmp.enabled=true
datasource.nyseg.enabled=false
datasource.rge.enabled=false

# Connection pools (same everywhere)
datasource.cmp.hikari.maximum-pool-size=2
datasource.cmp.hikari.minimum-idle=1
datasource.nyseg.hikari.maximum-pool-size=2
datasource.nyseg.hikari.minimum-idle=1
datasource.rge.hikari.maximum-pool-size=2
datasource.rge.hikari.minimum-idle=1

# Jackson hardening
spring.jackson.mapper.allow-coercion-of-scalars=false
spring.jackson.deserialization.accept-single-value-as-array=false
spring.jackson.deserialization.fail-on-null-for-primitives=true
spring.jackson.deserialization.fail-on-numbers-for-enums=true

# ffmpeg path (linux container)
#ffmpeg.path=/usr/bin/ffmpeg

